#:schema node_modules/wrangler/config-schema.json
name = "source-code-website"
compatibility_date = "2024-12-29"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"
